### ISSUE TITLE
Compilation error in url/url.go

### ISSUE THREAD

**Issue by gsmcwhirter** [asticode/go-astitools#4]
https://github.com/asticode/go-astitools/blob/7fb2f7207212054f20a98144406c389e5cae673d/url/url.go#L21 should not have err being returned from `filepath.ToSlash` (https://golang.org/pkg/path/filepath/#ToSlash)

**Comment by asticode** [comment]
You're right! Should be fixed now!

Thanks for letting me know.

Cheers
